# Generated by Django 4.2.30 on 2026-06-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_department_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='organization',
            name='director_name_en',
            field=models.CharField(blank=True, help_text='Masalan: B.Xolbutayev', max_length=255, null=True, verbose_name='Direktor ism-sharifi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='director_name_ru',
            field=models.CharField(blank=True, help_text='Masalan: B.Xolbutayev', max_length=255, null=True, verbose_name='Direktor ism-sharifi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='director_name_uz',
            field=models.CharField(blank=True, help_text='Masalan: B.Xolbutayev', max_length=255, null=True, verbose_name='Direktor ism-sharifi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region_en',
            field=models.CharField(blank=True, help_text='Masalan: Angor tumani', max_length=255, null=True, verbose_name='Tuman/Shahar nomi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region_ru',
            field=models.CharField(blank=True, help_text='Masalan: Angor tumani', max_length=255, null=True, verbose_name='Tuman/Shahar nomi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region_uz',
            field=models.CharField(blank=True, help_text='Masalan: Angor tumani', max_length=255, null=True, verbose_name='Tuman/Shahar nomi'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
